### ISSUE TITLE
nvAPI Test app

### ISSUE THREAD

**Issue by SveSop** [jp7677/dxvk-nvapi#18] opened 2021-06-12 12:29 UTC
I am hacking together a tiny testing app for testing nvAPI functions in both windows and wine. Maybe not that highly usable for gaming tests and stuff, but found it a useful thingy to test what replies one get from nvAPI for various functions.

It is compiled as a .exe, so it runs in both windows and wine. The goal being that i can verify and compare "things to expect" in a easy manner when putting together replies from nvapi. (I have a old GTX970 in a win10 box that i use for testing)

Use it if you like, or if you have easier/better tools - feel free to let me know :) Close this "issue" if you feel it is useless or not interesting tho. I felt it easy to add simple tests<->replies atleast.
[https://github.com/SveSop/nvtt](https://github.com/SveSop/nvtt)

**Comment by jp7677** [comment] 2021-06-12 13:21
Hi @SveSop this is actually pretty cool, thanks. I figured recently that having something for testing for preventing regressions at some point should become a thing, even with a relative simple code base as dxvk-nvapi. I have pretty good experiences with catch2 as a unit testing framework for c++, but for doing it properly, we would have to fake calls into dxgi and vulkan, eventually nvml. I haven’t had the time yet to dive into c++ frameworks for doing that and how easy it is to introduce those without going fully into dependency injection etc.  Until we have something like this, your project might fill this a gap. 
I’ll certainly give it a shot.

**Comment by SveSop** [comment] 2021-06-12 15:56
I have very little programming experience, so the little i do i try to keep simple. The reason for this tiny app was to easily add functions as well as being able to run it both in windows and wine without the need for any "outside framework" so to speak.

Anyway, i have come across a wee little snafu. I added a function not available in dxvk-nvapi, and calling this from the app seems to cause a page fault. This is kinda similar to what happens when i do some tests in proton with the nvml implementation posted (probably due to nvidia-ml not being available).

I do not have the same issues with my own nvapi implementation when this happens, so i do not know exactly what is going on. There does not seem to be issues when "unknown" functions are run from eg. GPU Caps Viewer tho, so the handling seems to work fine there. 

You can maybe fiddle a bit with it if you have the time? Just in case you can figure out if it is something strange that happens. The main difference from this app vs. a game is ofc that it is CLI based only without a gui.
[https://github.com/SveSop/nvtt/commit/74195638b171c6ff8f86f0eb7dbf204dbc5eec28](https://github.com/SveSop/nvtt/commit/74195638b171c6ff8f86f0eb7dbf204dbc5eec28)

**Comment by jp7677** [comment] 2021-06-12 19:57
QueryInterface returns `nullptr` (https://github.com/jp7677/dxvk-nvapi/blob/master/src/nvapi_interface.cpp#L34) for unknown methods. Can you try something like:
```c
    if (NvGetMemType) {
        ret = NvGetMemType(hdlGPU[0], &memtype);
        if(ret == NVAPI_OK){
          printf("Onboard memory type: GDDR%d\n", memtype<=8?5:6);
        }
    }
    else printf("NvAPI_GPU_GetRamType is not available!\n");
```

**Comment by SveSop** [comment] 2021-06-12 21:38
Yeah, seems to do the trick. Will look into rewriting those calls. 

Wine-staging implementation of nvapi returns a `NVAPI_ERROR` [https://github.com/wine-staging/wine-staging/blob/master/patches/nvapi-Stub_DLL/0001-nvapi-First-implementation.patch#L111](https://github.com/wine-staging/wine-staging/blob/master/patches/nvapi-Stub_DLL/0001-nvapi-First-implementation.patch#L111) on those "unknown and unimplemented" functions it seems.... or `NVAPI_ERROR` [https://github.com/wine-staging/wine-staging/blob/master/patches/nvapi-Stub_DLL/0001-nvapi-First-implementation.patch#L276](https://github.com/wine-staging/wine-staging/blob/master/patches/nvapi-Stub_DLL/0001-nvapi-First-implementation.patch#L276)

Thanks.

**Comment by jp7677** [comment] 2021-07-07 13:40
Hi @SveSop, I added a lot of tests recently including one that actually tests against installed DXVK and friends. Recent master builds a `nvapi64-tests.exe`. If you ran that with `nvapi64-tests.exe [.sysinfo-system]` in your wine prefix, do you get the same results like when running `nvtt`?

PS: The `nvapi64-tests.exe` executable does not depend on nvapi64.dll yet, everything is statically build. I'm still planning to look into that, but at least this project has a somewhat reliable test suite now.

**Comment by SveSop** [comment] 2021-07-07 20:40
> Hi @SveSop, I added a lot of tests recently including one that actually tests against installed DXVK and friends. Recent master builds a `nvapi64-tests.exe`. If you ran that with `nvapi64-tests.exe [.sysinfo-system]` in your wine prefix, do you get the same results like when running `nvtt`?
> 

Nice :) Maybe eventually have an option setting a wee bit more self-explanatory than [.sysinfo-system] if it is meant to be given as an option?

It does not seem as temperatures and clockfrequencies work for me..
```
NvAPI_GPU_GetThermalSettings: OK
    Current GPU temperature:2aC
NvAPI_GPU_GetAllClockFrequencies: OK
    Current graphics clock:124f80MHz
    Current memory clock:6acfc0MHz
    Current video clock:10eff0MHz
```
Expected result:
```
NvAPI_GPU_GetThermalSettings: OK
GPU Current Temperature: 42C
NvAPI_GPU_GetAllClockFrequencies: OK
GPU Current clock: 1200MHz
Memory Current clock: 7000MHz
Video Current clock: 1110MHz
```
Also tested GPU load by running `__GL_SYNC_TO_VBLANK=0 glxgears` (and verified that gpu was 100% with nvidia-smi)
```
NvAPI_GPU_GetDynamicPstatesInfoEx: OK
    GPU utilization:64%
    MEM utilization:1%
```
Expected result:
```
NvAPI_GPU_GetDynamicPstatesInfoEx: OK
GPU utilization: 100%
```
The ones i posted in "expected result" is what i get from `nvtt.exe`.

> PS: The `nvapi64-tests.exe` executable does not depend on nvapi64.dll yet, everything is statically build. I'm still planning to look into that, but at least this project has a somewhat reliable test suite now.

Since it is statically linked i guess it won't run in Windows, so it is not too easy to compare with "real" results. Hopefully that could be accomplished :)

Nice to have a test tho, so i will fiddle a bit more with it tomorrow and see if i can do some more comparisons :+1:

**Comment by jp7677** [comment] 2021-07-07 20:52
Thanks for the extensive description, seems that I need to convert from hex to decimal ;). I just (forced) pushed. Could you please try again?

**Comment by jp7677** [comment] 2021-07-08 08:37
> Since it is statically linked i guess it won't run in Windows, so it is not too easy to compare with "real" results. Hopefully that could be accomplished :)

Actually the `[.sysinfo-system]` tests are running just fine on Windows as long as you have the dxgi.dll from DXVK copied into the same folder as the test executable. The NVML methods are also returning what they are supposed to return as far as I can judge. The tests however indeed do not use any `nvapi64.dll`. So indeed no way (yet) to compare things.

About the argument name, that's just how tagging works in Catch2 (the unit testing framework), see https://github.com/jp7677/dxvk-nvapi/blob/master/tests/nvapi_sysinfo.cpp#L776 I guess I'll keep it like this since the real value is in running `nvapi64-tests` without any arguments, where all external calls (DXVK, Vulkan, NVML) are mocked and thus are no longer a requirement. That way we can run the test suite even in the gitlab runner (https://github.com/jp7677/dxvk-nvapi/blob/master/.github/workflows/artifacts.yml#L33).

**Comment by SveSop** [comment] 2021-07-08 09:15
Will do some more testing when i get home then

I have no idea how or what "catch2" is, so saying stuff like "all external calls (DXVK, Vulkan, NVML) are mocked and thus are no longer a requirement" does not mean much to me. Sorry for being dense.

Is it so that "running without arguments" just checks the lib for the functions without actually getting any real values, and running with the `[.sysinfo-system]` option makes nvapi get values and thus require live nVidia hardware.. something not available in the runner?

**Comment by jp7677** [comment] 2021-07-08 10:02
> Is it so that "running without arguments" just checks the lib for the functions without actually getting any real values, and running with the `[.sysinfo-system]` option makes nvapi get values and thus require live nVidia hardware.. something not available in the runner?

Catch2 is a unit test framework which let's you easily write, well, tests. So e.g. if you have some functions and want to validate that it behaves correctly with different conditions, writing a unit test is usually the way to go. Here is a simple example from the Catch2 project https://github.com/catchorg/Catch2/blob/devel/docs/tutorial.md#writing-tests
Using mocks (sometimes called fakes) allows you to easily fake objects and configure their behavior like it suits your test. See e.g. the test for `GetAllClockFrequencies` (https://github.com/jp7677/dxvk-nvapi/blob/master/tests/nvapi_sysinfo.cpp#L672). I'm running a test against the nvapi function, but before doing that, I created a fake `nvml` instance (to be specfiic, I create a new instance of a class that derives from the real nvml class (https://github.com/jp7677/dxvk-nvapi/blob/master/tests/nvapi_sysinfo_mocks.cpp#L65)) and configured it to return very specific hardcoded frequencies for just this test. So I'm configuring what NVML would do, calling the nvapi method and finally validating that nvapi returned what I expected. Due to the mocking I don't need to actual call into "nvml" but can just pretend to do so. The same principle is used for all tests except the `sysinfo-system test`. Thus I'm faking DVK, Vulkan and NVML if you like to test the behavior of nvapi methods without any dependency to the "real" driver/graphics stack, with one exception.

Running `nvapi64-tests` without arguments runs all tests except tests marked as to be skipped. The notation for having tests skipped by default is a dot in the tag, hence `[.sysinfo-system]` starts with a dot. Those skipped tests can still be executed by providing the test tag as argument. All that fancy things are part of Catch2 (https://github.com/catchorg/Catch2/blob/devel/docs/command-line.md#specifying-which-tests-to-run).

**Comment by SveSop** [comment] 2021-07-08 11:09
> Is it so that "running without arguments" just checks the lib for the functions without actually getting any real values, and running with the `[.sysinfo-system]` option makes nvapi get values and thus require live nVidia hardware.. something not available in the runner?

Oki, so i did get the gist of it then - Without the `[.sysinfo-system]` argument, the tests just report "dummy" values to verify that the functions are correct.

Could something like this be used for simplicity?
`CATCH_REGISTER_TAG_ALIAS( "[@real]", "[.sysinfo-system]" )`

Ill fiddle a bit with it and see if it actually makes more sense, or if it is just something in my head.

PS. For ME the real value lies in actually getting verifiably data tho... you can tell i am not a programmer hehe. I mean wine have horrible critical breaks ALL the time, even tho they have like a gazillion tests running every time a patch is being submitted, and most of the times when breakage is being fixed (even if the tests passed OK), it also means "fixing the tests". I'm maybe a bit negatively biased from that. (But i do understand that tests are being run because it is an impossible task to test all possible combinations for actual function all the time)

**Comment by jp7677** [comment] 2021-07-08 12:40
> Without the [.sysinfo-system] argument, the tests just report "dummy" values to verify that the functions are correct.
Actually there are two different sets of tests, most use the fakes, one test does real calls. The tags lets you control which tests to run.

Yeah, sure, in the end the real data has to show up. Having 100% succeeding tests is indeed no guarantee that you have no errors in your software. That said it can help a lot to simulate edge cases and might be a good insurance against introducing regressions while rewriting things.

**Comment by SveSop** [comment] 2021-07-08 13:59
Tests seems fine now. Thanks for the `DXVK_NVAPI_LOG_LEVEL=none` to skip clutter :+1: 

Btw `CATCH_REGISTER_TAG_ALIAS` also worked fine, so atleast it is an option to add an alias if remembering `[.sysinfo-system]` is cumbersome (like for me, that have the memory of a goldfish).

**Comment by SveSop** [comment] 2021-07-08 14:16
Interestingly enough, the "real" tests worked fine on Win10.
```
-------------------------------
Interface version:             R470
Driver version:                47111
Driver branch:                 v0.3-79-gbec3230+
Display driver version:        47111
Display driver adapter:        NVIDIA GeForce GTX 970
Display driver branch:         v0.3-79-gbec3230+
    ---------------------------
    GPU 0
    GPU type:                  Discrete
    Device ID:                 0x13c210de
    Full name:                 NVIDIA GeForce GTX 970
    Bus ID:                    1
    Physical framebuffer size: 4043MB
    LUID high part:            0x00000000
    LUID low part:             0x00007b41
    Architecture ID:           0x00000120
    Implementation ID:         0x00000004
    VBIOS version:             84.04.36.00.f1
    GPU utilization:           4%
    MEM utilization:           4%
    Current GPU temperature:   56C
    Current graphics clock:    1113MHz
    Current memory clock:      3505MHz
    Current video clock:       1025MHz
===============================================================================
All tests passed (12 assertions in 1 test case)
```

**Comment by jp7677** [comment] 2021-07-08 14:55
Thanks for the heads-up. Cool! Having exactly the same GPU and memory utilization is just coincidence I guess?

> Interestingly enough, the "real" tests worked fine on Win10.

Yes, this is supposed to work. This test does exactly the same what dxvk-nvapi does, thus using DXVK's dxgi, Vulkan and NVML directly.

**Comment by SveSop** [comment] 2021-07-09 07:22
> Thanks for the heads-up. Cool! Having exactly the same GPU and memory utilization is just coincidence I guess?
> 
Yes. 
I was running it through moonlight/nvidia gamestream, so it has a small degree of utilization.

5361bb491c54b5b0bc2af65f8ff6843ca5cd6e51 👍 Thanks.

**Comment by jp7677** [comment] 2021-07-09 17:21
I have again changed some things for the tests.
- Skipped and non-skipped is reversed, thus using no arguments starts the "real" test against local system
- The local system test now uses `nvapi64.dll`. This lets you run the test against NVIDIA's nvapi64.dll on Windows to compare values. For that case you need to ensure that no `nvapi64.dll` is present in the same folder as the test executable. When using wine-staging, `WINEDLLOVERRIDES=nvapi64=d` needs to be set to ensure that the native `nvapi64.dll` from this project is used. Wine's implementation fails due to missing methods.

**Comment by jp7677** [comment] 2021-09-28 05:40
I guess the system tests now offers similar functionality https://github.com/jp7677/dxvk-nvapi/blob/master/tests/nvapi_system.cpp

**Closed by jp7677** 2021-09-28 05:40 UTC
